version: '3.7'
services:
  nginx:
    container_name: familiars-note-nginx
    build:
      context: ./nginx
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ../../volumes/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ../../volumes/php/app/public:/var/www/html/public
    networks:
      - familiars-note-network
    restart: always
  php:
    container_name: familiars-note-php
    build:
      context: ./php
    volumes:
      - ../../volumes/php/app:/var/www/html
      - ../../volumes/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ../../volumes/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - familiars-note-network
    restart: always
  mariadb:
    container_name: familiars-note-mariadb
    build:
      context: ./mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - familiars-note-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    container_name: familiars-note-redis
    build:
      context: ./redis
    volumes:
      - redis-data:/data
    networks:
      - familiars-note-network
    restart: always
  maildev:
    container_name: familiars-note-maildev
    build:
      context: ./maildev
    ports:
      - ${MAILDEV_HTTP_PORT}:1080
    networks:
      - familiars-note-network
    restart: always
  adminer:
    container_name: familiars-note-adminer
    build:
      context: ./adminer
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - familiars-note-network
  redis-commander:
    container_name: redis-commander
    build:
      context: ./redis-commander
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - familiars-note-network
    environment:
      REDIS_HOSTS: Index0:redis:6379:0, Index1:redis:6379:1
  composer:
    container_name: familiars-note-composer
    build:
      context: ./composer
    volumes:
      - ../../volumes/php/app:/var/www/html
  npm:
    container_name: familiars-note-npm
    build:
      context: ./npm
    volumes:
      - ../../volumes/php/app:/root/app
  phpdoc:
    container_name: familiars-note-phpdoc
    build:
      context: ./phpdoc
    volumes:
      - ../../volumes/phpdoc/public:/var/www/html/public
      - ../../volumes/phpdoc/conf/phpdoc.xml:/var/www/html/phpdoc.xml
      - ../../volumes/php/app:/var/www/html/src
volumes:
  mariadb-data:
  redis-data:
networks:
  familiars-note-network: